/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedListsRouteImport } from './routes/_authenticated/lists'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedListsIdRouteImport } from './routes/_authenticated/lists.$id'
import { Route as AuthenticatedCopilotIdRouteImport } from './routes/_authenticated/copilot.$id'
import { Route as AuthenticatedBusinessIdRouteImport } from './routes/_authenticated/business.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListsRoute = AuthenticatedListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsIdRoute = AuthenticatedListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedListsRoute,
} as any)
const AuthenticatedCopilotIdRoute = AuthenticatedCopilotIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCopilotRoute,
} as any)
const AuthenticatedBusinessIdRoute = AuthenticatedBusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/copilot': typeof AuthenticatedCopilotRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/lists': typeof AuthenticatedListsRouteWithChildren
  '/business/$id': typeof AuthenticatedBusinessIdRoute
  '/copilot/$id': typeof AuthenticatedCopilotIdRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/copilot': typeof AuthenticatedCopilotRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/lists': typeof AuthenticatedListsRouteWithChildren
  '/business/$id': typeof AuthenticatedBusinessIdRoute
  '/copilot/$id': typeof AuthenticatedCopilotIdRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/lists': typeof AuthenticatedListsRouteWithChildren
  '/_authenticated/business/$id': typeof AuthenticatedBusinessIdRoute
  '/_authenticated/copilot/$id': typeof AuthenticatedCopilotIdRoute
  '/_authenticated/lists/$id': typeof AuthenticatedListsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agent'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/lists'
    | '/business/$id'
    | '/copilot/$id'
    | '/lists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agent'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/lists'
    | '/business/$id'
    | '/copilot/$id'
    | '/lists/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/lists'
    | '/_authenticated/business/$id'
    | '/_authenticated/copilot/$id'
    | '/_authenticated/lists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lists': {
      id: '/_authenticated/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthenticatedListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$id': {
      id: '/_authenticated/lists/$id'
      path: '/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AuthenticatedListsIdRouteImport
      parentRoute: typeof AuthenticatedListsRoute
    }
    '/_authenticated/copilot/$id': {
      id: '/_authenticated/copilot/$id'
      path: '/$id'
      fullPath: '/copilot/$id'
      preLoaderRoute: typeof AuthenticatedCopilotIdRouteImport
      parentRoute: typeof AuthenticatedCopilotRoute
    }
    '/_authenticated/business/$id': {
      id: '/_authenticated/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof AuthenticatedBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCopilotRouteChildren {
  AuthenticatedCopilotIdRoute: typeof AuthenticatedCopilotIdRoute
}

const AuthenticatedCopilotRouteChildren: AuthenticatedCopilotRouteChildren = {
  AuthenticatedCopilotIdRoute: AuthenticatedCopilotIdRoute,
}

const AuthenticatedCopilotRouteWithChildren =
  AuthenticatedCopilotRoute._addFileChildren(AuthenticatedCopilotRouteChildren)

interface AuthenticatedListsRouteChildren {
  AuthenticatedListsIdRoute: typeof AuthenticatedListsIdRoute
}

const AuthenticatedListsRouteChildren: AuthenticatedListsRouteChildren = {
  AuthenticatedListsIdRoute: AuthenticatedListsIdRoute,
}

const AuthenticatedListsRouteWithChildren =
  AuthenticatedListsRoute._addFileChildren(AuthenticatedListsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedListsRoute: typeof AuthenticatedListsRouteWithChildren
  AuthenticatedBusinessIdRoute: typeof AuthenticatedBusinessIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedListsRoute: AuthenticatedListsRouteWithChildren,
  AuthenticatedBusinessIdRoute: AuthenticatedBusinessIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
